platzigram/urls.py
""" Platzigram URLs module """
# Utilities
import os

# Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Codigo facilito   -   no causo ningun cambio
from django.conf.urls import url


urlpatterns = [
    #  problema at reverse lo pueden solucionar añadiendo al path de platzigram/urls.py lo siguiente:
    #path(r'', include('django.contrib.auth.urls')),
    # url : admin
    path('admin/', admin.site.urls, name='admin'),
    # url : posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # url : users
    path('', include(('users.urls', 'users'), namespace='users')),

    #path('posts/', include('platzigram.posts.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#from platzigram import views as local_views

#path('hello-world/', local_views.hello_world, name='hello_world'),
#path('hi/', local_views.hi, name='hi'),
#path('op/', local_views.operaciones, name='operations'),
#path('sol/', local_views.solucion_profe, name='solution'),
#path('age/<int:age>/<str:name>', local_views.age, name='age'),

posts/urls.py
""" Posts URLs. """

# Django
from django.urls import path
from django.views.generic import TemplateView

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view= views.PostsFeedListView.as_view(), 
        name='feed'
    ),
    path(
        route= 'new/',
        view= views.PostDetailView.as_view(), 
        name='create_post'
    ),
    path(
        route='posts/<int:pk>/', # <- Doc 2.2
        #route='posts/', # good
        view= views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        route='posts/trendingtopic',
        view=TemplateView.as_view(
            template_name='posts/trendingtopic.html'),
        name='trendingtopic'
    ),
]

users/urls.py
""" Users URLs. """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    # url : users
    path(   
        route='login/',
        view= views.LoginView.as_view(), 
        name='login'
    ),
    path(
        route= 'logout/', 
        view= views.LogoutView.as_view(), 
        name='logout'
    ),
    path(
        route= 'signup/', 
        view= views.SignupView.as_view(), 
        name='signup'
    ),
    path(
        route= 'me/profile/', 
        view= views.update_profile,
        #view = views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    # User's Posts: 
    path(
        route='users/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    
]

posts/models.py
"""Posts models."""

# Django
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    """Attributes of the post class"""
#Bring the foreing keys
#If the user is deleted, their posts will also be deleted [CASCADE]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
#If the profile is deleted, theirposts will also be deleted [CASCADE]
    #profile = models.ForeingKey(Profile, on_delete = models.CASCADE)  <- Ok or:
#                               /Users/models/Profile
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)
#Attributes
    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        """Return the title and username."""
        return '{} by @{}'.format(self.title,self.user.username)


    def image_tag(self):
        from django.utils.html import escape
        return u'<img src=%s />' % escape('posts/photos')

posts/forms.py
"""Forms of posts"""

# Django
from django.forms import ModelForm

# Models
from posts.models import Post


class PostForm(ModelForm):
    """Post model form."""
    class Meta:
        """Form settings.
        Configuración de la clase general"""

        model = Post
        fields = ['user', 'profile', 'title', 'photo']

posts/views.py
"""Posts views."""

# Django
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView
from django.urls import reverse, reverse_lazy

# Forms
from posts.forms import PostForm

# Models
from posts.models import Post


class PostDetailView(ListView, LoginRequiredMixin):
    """ Return a post with his details """
    template_name = 'posts/post_detail.html'
#/    model = Post ########### <--------------------- ?????????????????????????????????????
    
    #slug_field = 'pk'
    #Aslug_url_kwarg = 'pk' # post_id <= posts/urls.py <str:[name]>

    #ordering = ('-created')
    queryset = Post.objects.all()
    context_object_name = 'post'
    
    """    ERROR ENCONTRADO    
    ERROR ENCONTRADO    
    ERROR ENCONTRADO    
    ERROR ENCONTRADO    
    ERROR ENCONTRADO    
    ERROR ENCONTRADO    :::::::::::::      
    # Creacion de una url con kwargs: from django.urls import reverse
    url = reverse('users:detail', kwargs={'username': request.user.username})
    return redirect(url)
    """



class PostsFeedListView(ListView, LoginRequiredMixin):
    """ Return all published posts"""
    model = Post #########  <-------------------------------- ????????????????????
    template_name = "posts/feed.html"
    # Query args
    paginate_by = 8
    ordering = ('-created')
    queryset = Post.objects.all()
    # Context name
    context_object_name = 'posts'

    

"""
@login_required
def create_post(request):
    #create new post view
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            #create a post - save
            form.save()
            return redirect('posts:feed')
    else:
        form = PostForm()

    return render(
        request = request,
        template_name = 'posts/new.html',
        context = {
            'form': form,
            'user': request.user,
            'profile': request.user.profile,
        }
    )
"""
class PostDetailView(LoginRequiredMixin, CreateView):
    """ Create a new post """
    template_name  = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile
        return context
    

templates/posts/feed.html
<!-- Extend Boostrap -->
{% extends "base.html"%}

{% block head_content %}
    <title>Platzigram</title>
{% endblock %}
    
{% block container %}
    <div class="row">
        {% for post in posts %}
            {% include "posts/post_card.html" %}
        {% endfor %}
    </div>

    {% include 'pagination.html' %}            
{% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
<title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-6 pt-3 pb-3" id="profile-box">
                <h4 class="mb-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

{# NO HACER ESTO, YA QUE SE PUEDE MODIFICAR MEDIANTE EL FRONTEND Y PUBLICAR UN POST CON OTRO USUARIO (desde la vista se tienen que configurar estos datos)::: #}
                    <input type="hidden" name="user" value="{{ user.pk}}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />

                    {# Website field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                            value="{% if form.photo.errors %}{{ form.title.value }}{% endif %}"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                            class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                            type="file"
                            name="photo"
                            placeholder="photo"
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>

                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0 post-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>
    <!--<a href="{% url "posts:post_detail" post.pk %}" {# No muestra la imagen#} -->
        <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">
    
    <p class="mt-1 ml-2" >
        <a href="" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> 30 likes
    </p>
    <p class="ml-2 mt-0 mb-2">
        <b>{{ post.title }}</b> - <small>{{ post.created }}</small>
    </p>
</div>

templates/posts/post_detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/trendingtopic.html
{% extends "base.html" %}

{% block container %}
	<div class="row">
		<h1>Hola, mundo!!! Utilizanto un TemplateView generic! (easy)</h1>
	</div>
{% endblock %}