platzigram/urls.py
""" Platzigram URLs module """
# Utilities
import os

# Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Codigo facilito   -   no causo ningun cambio
from django.conf.urls import url


urlpatterns = [
    #  problema at reverse lo pueden solucionar añadiendo al path de platzigram/urls.py lo siguiente:
    #path(r'', include('django.contrib.auth.urls')),
    # url : admin
    path('admin/', admin.site.urls, name='admin'),
    # url : posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # url : users
    path('', include(('users.urls', 'users'), namespace='users')),

    #path('posts/', include('platzigram.posts.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#from platzigram import views as local_views

#path('hello-world/', local_views.hello_world, name='hello_world'),
#path('hi/', local_views.hi, name='hi'),
#path('op/', local_views.operaciones, name='operations'),
#path('sol/', local_views.solucion_profe, name='solution'),
#path('age/<int:age>/<str:name>', local_views.age, name='age'),

posts/urls.py
""" Posts URLs. """

# Django
from django.urls import path
from django.views.generic import TemplateView

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view= views.PostsFeedListView.as_view(), 
        name='feed'
    ),
    path(
        route= 'new/',
        view= views.PostDetailView.as_view(), 
        name='create_post'
    ),
    path(
        route='posts/<int:pk>/', # <- Doc 2.2
        #route='posts/', # good
        view= views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        route='posts/trendingtopic',
        view=TemplateView.as_view(
            template_name='posts/trendingtopic.html'),
        name='trendingtopic'
    ),
]

users/urls.py
""" Users URLs. """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    # url : users
    path(   
        route='login/',
        view= views.LoginView.as_view(), 
        name='login'
    ),
    path(
        route= 'logout/', 
        view= views.LogoutView.as_view(), 
        name='logout'
    ),
    path(
        route= 'signup/', 
        view= views.SignupView.as_view(), 
        name='signup'
    ),
    path(
        route= 'me/profile/', 
        view= views.update_profile,
        #view = views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    # User's Posts: 
    path(
        route='users/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5 enc" style="padding-top: 50px;">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">
        
        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url "posts:feed" %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>
        
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a name="profile-update" id="profile-update" href="{% url "users:detail" request.user.username %}">
                    {% if request.user.profile.picture %}
                        <img src="{{ request.user.profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" name="profile-picture" id="profile-picture" height="35" class="d-inline-block align-top rounded-circle"/>
                    {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a name="profile-plus" id="profile-plus" href="{% url "posts:create_post" %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a name="profile-logout" id="profile-logout" href="{% url "users:logout" %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous }}">
                Anterior
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>