platzigram/urls.py
""" Platzigram URLs module """
# Utilities
import os

# Django
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# Codigo facilito   -   no causo ningun cambio
from django.conf.urls import url


urlpatterns = [
    #  problema at reverse lo pueden solucionar añadiendo al path de platzigram/urls.py lo siguiente:
    #path(r'', include('django.contrib.auth.urls')),
    # url : admin
    path('admin/', admin.site.urls, name='admin'),
    # url : posts
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    # url : users
    path('', include(('users.urls', 'users'), namespace='users')),

    #path('posts/', include('platzigram.posts.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#from platzigram import views as local_views

#path('hello-world/', local_views.hello_world, name='hello_world'),
#path('hi/', local_views.hi, name='hi'),
#path('op/', local_views.operaciones, name='operations'),
#path('sol/', local_views.solucion_profe, name='solution'),
#path('age/<int:age>/<str:name>', local_views.age, name='age'),

posts/urls.py
""" Posts URLs. """

# Django
from django.urls import path
from django.views.generic import TemplateView

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view= views.PostsFeedListView.as_view(), 
        name='feed'
    ),
    path(
        route= 'new/',
        view= views.PostDetailView.as_view(), 
        name='create_post'
    ),
    path(
        route='posts/<int:pk>/', # <- Doc 2.2
        #route='posts/', # good
        view= views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        route='posts/trendingtopic',
        view=TemplateView.as_view(
            template_name='posts/trendingtopic.html'),
        name='trendingtopic'
    ),
]

users/urls.py
""" Users URLs. """

# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    # url : users
    path(   
        route='login/',
        view= views.LoginView.as_view(), 
        name='login'
    ),
    path(
        route= 'logout/', 
        view= views.LogoutView.as_view(), 
        name='logout'
    ),
    path(
        route= 'signup/', 
        view= views.SignupView.as_view(), 
        name='signup'
    ),
    path(
        route= 'me/profile/', 
        view= views.update_profile,
        #view = views.UpdateProfileView.as_view(),
        name='update_profile'
    ),
    # User's Posts: 
    path(
        route='users/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    
]

users/models.py
"""platzigram/users/models.py"""

# Django
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    website = models.URLField(max_length=200, blank=True)
    biografy = models.TextField(max_length=300,blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username

users/forms.py
""" User forms. """

# Django
from django import forms
from django.core.exceptions import ValidationError

# Models
from django.contrib.auth.models import User
from users.models import Profile

#utilities
import re


class ProfileForm(forms.Form):
    """Profile form"""
    
    # website is required by Middleware
    website = forms.URLField(max_length=200, required=True)
    # biografy isn't required by Middleware
    biografy = forms.CharField(max_length=400, required=False)
    # phone_number isn't required by Middleware
    phone_number = forms.CharField(required=False)
    # picture is required by Middleware
    picture = forms.ImageField(required=False)


    def clean_phone_number(self):
        """The phone number must be in the following format: (123) 456-7890 or 123-4567."""
        phone_number = self.cleaned_data['phone_number']

        first_option = re.search("^[(][0-9]{3}[)][ ][0-9]{3}[-][0-9]{4}$", phone_number)
        second_option = re.search("^[0-9]{3}[-][0-9]{4}$", phone_number)
        if first_option or second_option:
            return phone_number
        else:
            raise forms.ValidationError('Passwords do not match. :(')



class SignupForm(forms.Form):
    """ Sign up form. """
    username = forms.CharField(
        min_length=4, 
        max_length=50,
        label=False,
        widget=forms.TextInput(attrs={'placeholder':'username','class': 'form-control','required': True}))
    password = forms.CharField(
        min_length=6, 
        max_length=100,
        label=False,
        widget=forms.PasswordInput(attrs={'placeholder':'Password (min: 6)','class':'form-control', 'required': True}))
    password_confirmation = forms.CharField(
        min_length=6, 
        max_length=100, 
        label=False,
        widget=forms.PasswordInput(attrs={'placeholder':'Password (min: 6)','class':'form-control', 'required': True}))
    first_name = forms.CharField(
        min_length=3, 
        max_length=50,
        label=False,
        widget=forms.TextInput(attrs={'placeholder':'First name','class': 'form-control','required': True}))
    last_name = forms.CharField(
        min_length=3, 
        max_length=50,
        label=False,
        widget=forms.TextInput(attrs={'placeholder':'Last name','class': 'form-control','required': True}))
    email = forms.CharField(
        min_length=6, 
        max_length=100, 
        label=False,
        widget=forms.EmailInput(attrs={'placeholder':'Email','class': 'form-control', 'required': True}))

    def clean_username(self):
        """ Username must be unique. """
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('Username is already in use. :(')
        return username


    def clean(self):
        """ Verify password confirmation match. """
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match. :(')
        return data

    
    def save(self):
        """ Create user and profile. """
        data = self.cleaned_data
# password_confirmation isn't need
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
"""Users views."""

# Django
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic import FormView, UpdateView

from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin 

# Models
from django.contrib.auth.models import User
from users.models import Profile
from posts.models import Post

# Forms
from users.forms import ProfileForm, SignupForm

# Create your views here.

class PostDetailView(DetailView, LoginRequiredMixin):
    """ User's Posts detail view. """
    template_name = "users/post_detail.html"
    slug_fielf = 'id'
    slug_url_kwarg = 'id'

    queryset = Post.objects.all()
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        """ Add user's posts to context """
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        #context["posts"] = Post.objects.filter(title=title)
        context["posts"] = Post.objects.get(id= post.id)
        return context
    

class UserDetailView(DetailView, LoginRequiredMixin):
    """ User detail view. """
    template_name = "users/detail.html"
    slug_field = 'username' # <- el username es un campo unico en nuestro modelo
    slug_url_kwarg = 'username' # <- [username] === users/urls.py /path/route/str:[username]
    # queryset : trae a todos los usuarios (Django concatena todas las peticiones (todos los usuarios)) para hacer el query más especiífico y Django busca el objeto ahí.
    queryset = User.objects.all()

    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user
        user = self.get_object()
        # Query
        # from posts.models import Post
        context["posts"] = Post.objects.filter(user=user).order_by('-created')
        return context
    

class UpdateProfileView(UpdateView, LoginRequiredMixin):
    """User Update."""
    template_name = "users/update_profile.html"
    model = Profile
    fields = ['website', 'phone_number', 'biografy']
    #success_url = "users:detail"

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile
    
#    def form_valid(self, form):
        """If the form is invalid, render the invalid form."""
#        if form['phone_numbre']== 0:
#            return self.render_to_response(self.get_context_data(form=form))
#        else:
#            return 1
    
    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse_lazy('users:detail', kwargs={'username': username})


@login_required
def update_profile(request):
    """Update a users's profile view."""
    profile = request.user.profile

    if request.method == 'POST':
        # form is a instance of ProfileForm with request
        # request.FILES es utilizado para recibir los archivos, desde el FORM enctype="multipart/form-data"
        form = ProfileForm(request.POST, request.FILES)
        
        #print(form.cleaned_data)
        if form.is_valid():
            #print(form.cleaned_data)
            data = form.cleaned_data
            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biografy = data['biografy']
            #profile.picture = data['picture']
            #print("error------------------------------------------- {}".format(data['picture']))
            if data['picture'] == None:
                pass
            else:
                profile.picture = data['picture']
            profile.save()

            # Creacion de una url con kwargs: from django.urls import reverse
            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect(url)

        else:
            print("NO++++++++++++++++++++++++++++++++++++++++++++++++++")
    else:
        form = ProfileForm()

    return render(
        request=request, 
        template_name='users/update_profile.html',
        context={
            'profile': profile,
            'user': request.user,
            'form': form
        }
    )


class LoginView(auth_views.LoginView):
    """Login view."""
    redirect_authenticated_user= True
    template_name = 'users/login.html'


class LogoutView(auth_views.LogoutView, LoginRequiredMixin):
    """Logout view."""
    # this template don't used.
    template_name = 'registration/logged_out.html'

class SignupView(auth_views.LoginView ,FormView):
    """Signup a user."""
    login_url = '/'
    redirect_field_name = 'posts:feed'
    redirect_authenticated_user = True


    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        """Solucción básica:
        form.save()
        return super().form_valid(form)
        """
        """ Save form data and login new user."""
        form.save()

        username = form['username'].value()
        password = form['password'].value()

        user = authenticate(
            self.request,
            username = username,
            password = password
        )

        login(self.request, user)
        return super().form_valid(form)

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>


    <div class="container h-100">

        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">

                {% block container %}
                {% endblock%}
            </div>
        </div>
    </div>

</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username}}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    {{ user.username }}
                    {% if user == request.user %}
                        <a
                            href="{% url "users:update_profile" %}"
                            class="ml-5 btn btn-sm btn-outline-info"
                        >
                            Editar perfil
                        </a>
                    {% else %}
                        <a
                            href=""
                            class="ml-5 btn btn-sm btn-primary"
                        >
                            Follow
                        </a>
                    {% endif %}
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ user.profile.posts_count }}123</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.followers }}1,401</b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>{{ user.profile.following }}491</b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biografy }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pl-5 d-flex justify-content align-items-center">
                <a href="" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Platzigram sign in</title>
{% endblock %}

{% block container %}
    <!-- Si la variable error contiene algo: -->
    {% if form.errors %}
        <p class="alert alert-danger">
        Your username or password didn't match :(, please try again.
        </p>
    {% endif %}
    <!-- action === 
                    NULL (sin action) || 
                    ="." ||
                    =/users/login ||
                    ="{ % url "name" % }"-->
    <form method="POST" accion="{% url "users:login" %}">
        {% csrf_token %}
        <!-- = request.user -->
        <div>
        
        </div>
        <div class="form-group">
            <input class="form-control mb-2" type="text" placeholder="Username" name="username" />
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>
        <button class="btn btn-primary btn-block mt-5" type="submit" name="signin">Sign In!</button>
    </form>
    
    <button class="btn btn-primary btn-block mt-5" onclick="location.href = '{% url "users:signup" %}'">Sign Up!</button>
    
    <p class="mt-4">Don't have an acount yet? <a href="{% url "users:signup" %}">Sign up here.</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Sign Up</title>
{% endblock %}

{% block container %}
    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        
        {{ form.as_p }}
        
        <button class="btn btn-primary btn-block mt-5" type="submit">Sign Up!</button>

    </form>
{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>{{ request.user.username }} | Update</title>
{% endblock %}

{% block container %}

<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6  p-4" id="profile-box">

<!-- enctype : El form recive varios tipos de datos (xej: files) -->
<!-- Los archivos por formulario no se envian por request.POST, se envian por request.FILE en la vista -->
            <form action="{% url 'users:update_profile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else %}
                        <img src="{% static 'img/default-profile.png' %}" 
                            class="rounded-circle" 
                            height="50" 
                        />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4"> Hello {{ request.user.username}} | {{ request.user.get_full_name }}</h5>
                        <p class="ml-4">
                            <input 
                                type="file" 
                                name="picture" 
                                id="picture"
                            />
                        </p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{ error }}
                    </div>
                {% endfor %}
                
                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input 
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}" 
                        type="url" 
                        name="website" 
                        id="website" 
                        placeholder="Website"
                        required="true"
                        value="
                        {% if form.errors %}
                            {# Si hay errores, imprime el valor ingresado erroneo #}
                            {{ form.website.value }}
                        {% else %}
                            {# Si no hay errores, imprime el valor guardado del formulario #}
                            {{ profile.website }}
                        {% endif %}"/>
                    <div class="invalid-feedback">
                        {% for error in form.website.error %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                        class="form-control {% if form.biografy.errors %}is-invalid{% endif %}" 
                        name="biografy"
                        placeholder="Biography"
                        id="biografy">{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biografy }}{% endif %}</textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biografy.error %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-control">
                    <label>Phone number</label>
                    <input 
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number }}{% else %}{{ profile.phone_number }}{% endif %}"/>
                    <div class="invalid-feedback">{% for error in form.phone_number.error %}{{ error }}{% endfor %}</div>
                </div>

                <button type="submit" class="btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}